import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Main from '../components/Main';
import FullLine from '../components/UI/FullLine';
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Portfolio - Homepage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      {/* TODO TRANSITION header disapear */}
      <Header />
      <FullLine className='opacity-10' />
      <Main />
      <Footer />
    </>
  );
};

export default Home;
